import React,{useEffect,useState}from"react";
import{ArrowLeft,Eye,RotateCcw,Volume2,VolumeX}from"lucide-react";
import"./TeenPattiPractice.css";
import "./TeenPattiResult.css";
import{compareHands,evaluateHand,isRedSuit,rankLabel}from"./teenPattiEngine.jsx";
import{teenPattiService}from"./teenPattiService.jsx";
function Card({card,hidden,index}){return hidden?<span className="tp-card back" style={{"--i":index}}><i>♛</i></span>:<span className={`tp-card ${isRedSuit(card.suit)?"red":"black"}`} style={{"--i":index}}><b>{rankLabel(card.rank)}</b><i>{card.suit}</i><small>{card.suit}</small></span>}
const Cards=({cards,hidden})=><div className="tp-cards">{cards.map((c,i)=><Card key={c.id} card={c} hidden={hidden} index={i}/>)}</div>;
export default function TeenPattiPractice(){const[state,setState]=useState(null),[sound,setSound]=useState(true);const begin=async(session=null)=>{const base=session||await teenPattiService.startSession();setState(await teenPattiService.dealRound(base.balance,base.history))};useEffect(()=>{begin()},[]);
const finish=(activeOverride=null)=>setState(old=>{const active=activeOverride||old.active,players=["user","bot1","bot2"].filter(k=>active[k]);let winners=[players[0]];players.slice(1).forEach(p=>{const c=compareHands(old.hands[p],old.hands[winners[0]]);if(c>0)winners=[p];else if(c===0)winners.push(p)});const share=Math.floor(old.pot/winners.length),userWon=winners.includes("user"),winner=winners.map(x=>x==="user"?"YOU":x==="bot1"?"RAJA BOT":"ACE BOT").join(" & ");const next={...old,active,phase:"result",winner,balance:old.balance+(userWon?share:0),message:userWon?`YOU WON ${share} COINS`:`${winner} WINS`,history:[{winner,pot:old.pot},...old.history].slice(0,8)};teenPattiService.saveRound(next);return next});
const see=()=>setState(o=>({...o,seen:true,message:evaluateHand(o.hands.user).name}));const pack=()=>finish({...state.active,user:false});
const chaal=()=>setState(old=>{const stake=old.seen?20:10;if(old.balance<stake)return{...old,message:"NOT ENOUGH COINS"};const active={...old.active};let botStake=0;["bot1","bot2"].forEach(bot=>{if(!active[bot])return;const h=evaluateHand(old.hands[bot]);if(old.chaals>0&&h.level===1&&h.values[0]<11)active[bot]=false;else botStake+=10});const chaals=old.chaals+1,next={...old,active,chaals,balance:old.balance-stake,pot:old.pot+stake+botStake,message:"BOTS PLAYED • YOUR TURN"};if(Object.values(active).filter(Boolean).length===1||chaals>=3)setTimeout(()=>finish(active),350);return next});
const show=()=>{const cost=state.seen?20:10;if(state.balance<cost)return;setState(o=>({...o,balance:o.balance-cost,pot:o.pot+cost,message:"SHOWING CARDS..."}));setTimeout(()=>finish(),320)};if(!state)return null;const reveal=state.phase==="result";
return <main className="tp-page"><header className="tp-header"><button onClick={()=>window.history.back()}><ArrowLeft/></button><div><small>FREE PRACTICE TABLE</small><strong>TEEN <em>PATTI</em></strong></div><button onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}</button></header><section className="tp-wallet"><div><small>PRACTICE COINS</small><b>◆ {state.balance}</b></div><div><small>BOOT</small><b>{state.boot}</b></div><button onClick={()=>begin({balance:1000,history:[]})}><RotateCcw/> RESET</button></section><section className="tp-table"><div className="tp-felt-ring"/><div className={`tp-seat bot-one ${state.active.bot1?"":"folded"} ${reveal&&state.winner?.includes("RAJA BOT")?"winner-seat":""}`}><div className="tp-avatar">R</div><strong>RAJA BOT</strong><small>{state.active.bot1?reveal?evaluateHand(state.hands.bot1).name:"BLIND":"PACK"}</small><Cards cards={state.hands.bot1} hidden={!reveal}/></div><div className={`tp-seat bot-two ${state.active.bot2?"":"folded"} ${reveal&&state.winner?.includes("ACE BOT")?"winner-seat":""}`}><div className="tp-avatar">A</div><strong>ACE BOT</strong><small>{state.active.bot2?reveal?evaluateHand(state.hands.bot2).name:"BLIND":"PACK"}</small><Cards cards={state.hands.bot2} hidden={!reveal}/></div><div className="tp-pot"><small>TABLE POT</small><b>◆ {state.pot}</b><span>{state.message}</span></div><div className={`tp-seat user-seat ${state.active.user?"":"folded"} ${reveal&&state.winner?.includes("YOU")?"winner-seat":""}`}><div className="tp-avatar">Y</div><strong>YOU</strong><small>{state.seen||reveal?evaluateHand(state.hands.user).name:"BLIND"}</small><Cards cards={state.hands.user} hidden={!state.seen&&!reveal}/></div>{reveal&&<div className="tp-result"><small>ROUND RESULT</small><h2>{state.winner}</h2><p>{state.message}</p><button onClick={()=>begin(state)}>DEAL AGAIN</button></div>}</section><section className="tp-actions"><button className="pack" onClick={pack} disabled={reveal}>PACK</button><button className="see" onClick={see} disabled={state.seen||reveal}><Eye/> SEE</button><button className="chaal" onClick={chaal} disabled={reveal}><small>CHAAL</small><b>◆ {state.seen?20:10}</b></button><button className="show" onClick={show} disabled={reveal||state.chaals<1}>SHOW</button></section><section className="tp-history"><span>RECENT</span>{state.history.length?state.history.map((x,i)=><i key={i}>{x.winner} • {x.pot}</i>):<small>No rounds yet</small>}</section></main>}
